apiVersion: v2
name: argocd-wrapper
description: Minimal wrapper chart to install and expose Argo CD on GKE
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
  - name: argo-cd
    version: ">=6.0.0 <9.0.0"
    repository: "https://argo.github.io/argo-helm"
